kind: ImageStreamList
apiVersion: v1
metadata:
  name: daas-image-streams
  annotations:
    description: ImageStream definitions for DaaS 0.1
    openshift.io/provider-display-name: 'Red Hat, Inc.'
items:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: daas-modeler-ubi8
      annotations:
        openshift.io/display-name: DaaS Modeler 0.1
        openshift.io/provider-display-name: 'Red Hat, Inc.'
    spec:
      tags:
        - name: '0.1'
          annotations:
            description: DaaS 0.1 Modeler image
            iconClass: icon-jboss
            tags: 'daas,kie,kiegroup,jboss'
            supports: 'daas:0.1'
            version: '0.1'
          referencePolicy:
            type: Local
          from:
            kind: DockerImage
            name: 'quay.io/kiegroup/daas-modeler-ubi8:0.1'
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: daas-acceptor-ubi8
      annotations:
        openshift.io/display-name: DaaS Acceptor 0.1
        openshift.io/provider-display-name: 'Red Hat, Inc.'
    spec:
      tags:
        - name: '0.1'
          annotations:
            description: DaaS 0.1 Acceptor image
            iconClass: icon-jboss
            tags: 'daas,kie,kiegroup,jboss'
            supports: 'daas:0.1'
            version: '0.1'
          referencePolicy:
            type: Local
          from:
            kind: DockerImage
            name: 'quay.io/kiegroup/daas-acceptor-ubi8:0.1'
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: daas-executor-ubi8-s2i
      annotations:
        openshift.io/display-name: DaaS Executor S2I 0.1
        openshift.io/provider-display-name: 'Red Hat, Inc.'
    spec:
      tags:
        - name: '0.1'
          annotations:
            description: DaaS 0.1 Executor S2I image
            iconClass: icon-jboss
            tags: 'daas,kie,kiegroup,jboss,s2i'
            supports: 'daas:0.1'
            version: '0.1'
          referencePolicy:
            type: Local
          from:
            kind: DockerImage
            name: 'quay.io/kiegroup/daas-executor-ubi8-s2i:0.1'
