apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: daas-workflow
spec:
  serviceAccountName: pipeline
  triggers:
    - name: daas
      bindings:
        - ref: daas-workflow-binding
      template:
        name: daas-workflow-template
