apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: daas-template
spec:
  params:
    - name: appname
      type: string
      description: The application name
      default: 'myapp'
    - name: native
      type: string
      description: If true build native image
      default: 'true'
    - name: imagesuffix
      type: string
      description: The suffix for executor image tag
      default: '-native:latest'
    - name: builderimage
      type: string
      description: The base image used for packaging compiled runner
      default: 'quay.io/kiegroup/kogito-quarkus-ubi8:latest'
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: daas-$(params.appname)-$(uid)
      spec:
        workspaces:
          - name: work-dir
            persistentVolumeClaim:
              claimName: daas-work-dir-pvc
            subPath: work
          - name: repo-dir
            persistentVolumeClaim:
              claimName: daas-work-dir-pvc
            subPath: maven
        pipelineSpec:
          workspaces:
            - name: work-dir
            - name: repo-dir
          tasks:
            - name: compile-build-and-push
              params:
                - name: APPLICATION_NAME
                  value: '$(params.appname)'
                - name: TLSVERIFY
                  value: 'false'
                - name: EXECUTOR_IMAGE_TAG
                  value: 'image-registry.openshift-image-registry.svc:5000/kiegroup/daas-executor-ubi8-$(params.appname)$(params.imagesuffix)'
                - name: BUILDER_IMAGE_TAG
                  value: '$(params.builderimage)'
                - name: NATIVE
                  value: '$(params.native)'
              workspaces:
                - name: source
                  workspace: work-dir
                - name: repo
                  workspace: repo-dir
              taskRef:
                name: s2i-kogito
                kind: ClusterTask
