apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: daas-workflow-binding
spec:
  params:
    - name: appname
      value: $(body.appname)
    - name: imagenamespace
      value: $(body.envname)
